<?php

namespace Dropplets;

/**
 * Reads and writes site configuration.
 *
 * The original built config.php by concatenating raw POST values into PHP
 * source, which allowed code injection (single quotes were only HTML-encoded,
 * the wrong context for a PHP string literal). This version serializes the
 * config array with var_export(), which escapes correctly for every value,
 * and stores it OUTSIDE the web root so the password hash is never fetchable
 * over HTTP even on non-Apache servers.
 */
final class Config
{
    private string $configFile;

    /** Sensible defaults used before a config exists. */
    public const DEFAULTS = [
        'name'         => '',
        'info'         => '',
        'domain'       => '',
        'OGImage'      => '',
        'footer'       => '',
        'headerInject' => '',
        'password'     => '',
        'template'     => 'liquid-new',
        'postsPerPage' => 6,
        'basePath'     => '',
        'timezone'     => 'America/New_York',
        'I18N'         => 'en_US',
    ];

    public function __construct(string $dataDir)
    {
        $this->configFile = rtrim($dataDir, '/') . '/config.php';
    }

    public function exists(): bool
    {
        return is_file($this->configFile);
    }

    /**
     * Load the stored config merged over defaults, or defaults alone.
     *
     * @return array<string,mixed>
     */
    public function load(): array
    {
        if (!$this->exists()) {
            return self::DEFAULTS;
        }
        $stored = require $this->configFile;
        if (!is_array($stored)) {
            return self::DEFAULTS;
        }
        return array_merge(self::DEFAULTS, $stored);
    }

    /**
     * Persist the config array safely.
     *
     * @param array<string,mixed> $config
     */
    public function save(array $config): bool
    {
        $config = array_merge(self::DEFAULTS, $config);

        $export = var_export($config, true);
        $content = "<?php\n"
            . "// Generated by Dropplets. Do not edit while the site is live.\n"
            . "// This file lives outside the web root and must never be served.\n"
            . "return {$export};\n";

        $dir = dirname($this->configFile);
        if (!is_dir($dir) && !mkdir($dir, 0750, true) && !is_dir($dir)) {
            return false;
        }

        // Write atomically so a half-written config can never be loaded.
        $tmp = $this->configFile . '.' . bin2hex(random_bytes(6)) . '.tmp';
        if (file_put_contents($tmp, $content, LOCK_EX) === false) {
            return false;
        }
        @chmod($tmp, 0640);
        return rename($tmp, $this->configFile);
    }
}
